// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pay.proto

package pay

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayReq) Reset()         { *m = PayReq{} }
func (m *PayReq) String() string { return proto.CompactTextString(m) }
func (*PayReq) ProtoMessage()    {}
func (*PayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{0}
}

func (m *PayReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayReq.Unmarshal(m, b)
}
func (m *PayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayReq.Marshal(b, m, deterministic)
}
func (m *PayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayReq.Merge(m, src)
}
func (m *PayReq) XXX_Size() int {
	return xxx_messageInfo_PayReq.Size(m)
}
func (m *PayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PayReq.DiscardUnknown(m)
}

var xxx_messageInfo_PayReq proto.InternalMessageInfo

func (m *PayReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PayReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *PayReq) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PayReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PayReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type PayRes struct {
	Paid                 bool     `protobuf:"varint,1,opt,name=paid,proto3" json:"paid,omitempty"`
	Captured             bool     `protobuf:"varint,3,opt,name=captured,proto3" json:"captured,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayRes) Reset()         { *m = PayRes{} }
func (m *PayRes) String() string { return proto.CompactTextString(m) }
func (*PayRes) ProtoMessage()    {}
func (*PayRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0564d675d5c516e0, []int{1}
}

func (m *PayRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayRes.Unmarshal(m, b)
}
func (m *PayRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayRes.Marshal(b, m, deterministic)
}
func (m *PayRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayRes.Merge(m, src)
}
func (m *PayRes) XXX_Size() int {
	return xxx_messageInfo_PayRes.Size(m)
}
func (m *PayRes) XXX_DiscardUnknown() {
	xxx_messageInfo_PayRes.DiscardUnknown(m)
}

var xxx_messageInfo_PayRes proto.InternalMessageInfo

func (m *PayRes) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *PayRes) GetCaptured() bool {
	if m != nil {
		return m.Captured
	}
	return false
}

func (m *PayRes) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*PayReq)(nil), "pay.PayReq")
	proto.RegisterType((*PayRes)(nil), "pay.PayRes")
}

func init() { proto.RegisterFile("pay.proto", fileDescriptor_0564d675d5c516e0) }

var fileDescriptor_0564d675d5c516e0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbd, 0x6a, 0xc3, 0x30,
	0x10, 0xc7, 0x6b, 0x39, 0x16, 0xce, 0x05, 0x3a, 0x1c, 0xa5, 0x88, 0x4c, 0xc6, 0x74, 0xc8, 0x94,
	0x21, 0x7d, 0x83, 0x76, 0x2e, 0x18, 0x8d, 0xdd, 0xae, 0x91, 0x48, 0x45, 0xb1, 0xa4, 0xca, 0xf2,
	0x20, 0xe8, 0xc3, 0x17, 0xcb, 0x26, 0x68, 0xbb, 0x9f, 0x74, 0xc7, 0xff, 0x03, 0xf6, 0x9e, 0xd2,
	0xd9, 0x07, 0x17, 0x1d, 0xd6, 0x9e, 0x52, 0xff, 0x07, 0x7c, 0xa0, 0x24, 0xf5, 0x2f, 0x3e, 0x02,
	0x33, 0x4a, 0x54, 0x5d, 0x75, 0xaa, 0x25, 0x33, 0x0a, 0x9f, 0xa0, 0x89, 0xee, 0x47, 0x5b, 0xc1,
	0xba, 0xea, 0xb4, 0x97, 0x2b, 0xe0, 0x33, 0x70, 0x1a, 0xdd, 0x6c, 0xa3, 0xa8, 0xf3, 0xe6, 0x46,
	0x88, 0xb0, 0xb3, 0x34, 0x6a, 0xb1, 0xcb, 0xcb, 0x79, 0xc6, 0x0e, 0x0e, 0x4a, 0x4f, 0xd7, 0x60,
	0x7c, 0x34, 0xce, 0x8a, 0x26, 0x7f, 0x95, 0x4f, 0xfd, 0xb0, 0xa9, 0x4f, 0xcb, 0xbd, 0xa7, 0x4d,
	0xbf, 0x95, 0x79, 0xc6, 0x23, 0xb4, 0x57, 0xf2, 0x71, 0x0e, 0x5a, 0x65, 0xb5, 0x56, 0xde, 0xb9,
	0xf0, 0xc1, 0x4a, 0x1f, 0x97, 0x0b, 0xc0, 0x40, 0xe9, 0x83, 0x2c, 0xdd, 0x74, 0xc0, 0x17, 0xe0,
	0xef, 0xdf, 0x14, 0x6e, 0x1a, 0x0f, 0xe7, 0x25, 0xf8, 0x1a, 0xf5, 0x58, 0xc0, 0xd4, 0x3f, 0xbc,
	0x35, 0x9f, 0x4b, 0x15, 0x5f, 0x3c, 0xd7, 0xf2, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x52, 0xe3,
	0x97, 0x7f, 0x23, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PayManagerClient is the client API for PayManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayManagerClient interface {
	Charge(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayRes, error)
}

type payManagerClient struct {
	cc *grpc.ClientConn
}

func NewPayManagerClient(cc *grpc.ClientConn) PayManagerClient {
	return &payManagerClient{cc}
}

func (c *payManagerClient) Charge(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayRes, error) {
	out := new(PayRes)
	err := c.cc.Invoke(ctx, "/pay.PayManager/Charge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayManagerServer is the server API for PayManager service.
type PayManagerServer interface {
	Charge(context.Context, *PayReq) (*PayRes, error)
}

// UnimplementedPayManagerServer can be embedded to have forward compatible implementations.
type UnimplementedPayManagerServer struct {
}

func (*UnimplementedPayManagerServer) Charge(ctx context.Context, req *PayReq) (*PayRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Charge not implemented")
}

func RegisterPayManagerServer(s *grpc.Server, srv PayManagerServer) {
	s.RegisterService(&_PayManager_serviceDesc, srv)
}

func _PayManager_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayManagerServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pay.PayManager/Charge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayManagerServer).Charge(ctx, req.(*PayReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PayManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pay.PayManager",
	HandlerType: (*PayManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _PayManager_Charge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pay.proto",
}
